version: '3.8'

services:
  app:
    build:
      context: .          # On construit l'image Ã  partir du Dockerfile dans le dossier courant
    container_name: streamlit_app
    ports:
      - "8501:8501"       # Expose Streamlit sur le port local 8501
    volumes:
      - .:/app            # Monte ton code dans le conteneur (pour pouvoir modifier sans rebuild)
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
